---
- name: Provisioning vagrant
  hosts:
    - vagrant
  become: true
  roles:
    - docker
#    - host
#    - ddns
#    - vpn
#    - webserver
#    - database
#    - wiki
#    - password-manager
#    - portainer
#    - minecraft
#    - reverse-proxy
#    - yumme
